### ISSUE TITLE
Sync with asset references proposal

### ISSUE THREAD

**Issue by mikesamuel** [mikesamuel/dynamic-import-host-adjustment#1]
+@bmeck
+@sebmarkbage 

Per [feedback from the last in-person meeting](https://github.com/rwaldron/tc39-notes/blob/master/meetings/2019-07/july-25.md#dynamic-import-host-adjustment-for-stage-1-or-2):

> BFS: I’d like to note this has an effect on AssetReferences. They’d also require a similar change for non-string types, since they encode information on where the asset reference is formed, they're not something which can be forged or done with a string identity.

this proposal may overlap with [asset references](https://github.com/sebmarkbage/ecmascript-asset-references).

Off the top of my head, points of overlap include:
* Both may affect the HostImportModuleDynamically to FinishDynamicImport flow.
* Asset references may benefit from the changes to dynamic import to not stringify early.
* If github.com/wicg/trusted-types defines a *TrustedModuleSpecifier* type then `new AssetReference(...)` should not stringify the value assigned to its `[AssetSpecifier]` internal slot.

**Comment by bmeck** [comment]
@mikesamuel can you clarify

> If github.com/wicg/trusted-types defines a TrustedModuleSpecifier type then new AssetReference(...) should not stringify the value assigned to its [AssetSpecifier] internal slot

If the value in the TrustedModuleSpecifier is downgraded to not be trusted (since it becomes a string), what is the problem? Are TrustedModuleSpecifiers not expected to have a URL based location on the web?

**Comment by sebmarkbage** [comment]
It seems to me that the specifier shouldn't necessarily be a TrustedModuleSpecifier. Instead, it is the whole AssetReference that is trusted. The tuple would be of a trusted type.

Although I'm not sure Asset References should necessarily automatically be trusted because they're static. A policy can prevent a particular url or path to be disallowed from a particular subgraph even if the path to it is statically specified. To avoid mistakes of taking on insecure dependencies.

For this to work the Asset References need some way to attain a policy that they produce trusted values from.

**Comment by bmeck** [comment]
@sebmarkbage if we are talking policies, there are a lot of other things a policy might wish to embed other than just if a specifier is allowed to be resolved (final path / integrity+MIME of resource body / etc.). It might be better to just say this is all host meta-data and leave it up to policy from the host to determine the right data to include.

**Comment by mikesamuel** [comment]
Sorry for taking so long to respond.

> If the value in the TrustedModuleSpecifier is downgraded to not be trusted (since it becomes a string), what is the problem?

That fails safe w.r.t. integrity but not availability; if a properly made trust decision is not respected, then it's harder to convince teams to adopt measures that make trust decisions explicit and auditable.

> It seems to me that the specifier shouldn't necessarily be a TrustedModuleSpecifier. Instead, it is the whole AssetReference that is trusted. The tuple would be of a trusted type.

Fair enough.

**Comment by mikesamuel** [comment]
I think issue #3 and issue #4 cover the main points.
